[build]
  base = "client"
  command = "NODE_OPTIONS=--max_old_space_size=4096 npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://www.easydrivecanada.com/*"
  to = "https://easydrivecanada.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.easydrivecanada.com/*"
  to = "https://easydrivecanada.com/:splat"
  status = 301
  force = true
